stages:
  - test
  - stats
  - deploy
  - release

default:
  image: python:3.7-buster
  before_script:
    - apt update
    - apt install rsync ssh -y
    - pip install ci-scripts
    - mkdir -p ~/.ssh
    - echo "$SERVER_ACCESS_KEY" > ~/.ssh/id_rsa
    - chmod 0600 ~/.ssh/id_rsa
    - ssh-keyscan -H netcup.namibsun.net >> ~/.ssh/known_hosts

stylecheck:
  stage: test
  tags: [docker]
  script:
    - python-codestyle-check

testing:
  stage: test
  tags: [python3]
  before_script: []
  script:
    - echo "$SERVER_ACCESS_KEY" > id_rsa
    - chmod 0600 id_rsa
    - touch b
    - rsync -e "ssh -i id_rsa" b hermann@netcup.namibsun.net:/home/hermann

testing2:
  stage: test
  tags: [docker]
  image: ubuntu:18.04
  before_script:
    - apt update
    - apt install rsync ssh -y
  script:
    - echo "$SERVER_ACCESS_KEY" > id_rsa
    - chmod 0600 id_rsa
    - cat id_rsa
    - touch c
    - rsync -e "ssh -i id_rsa -oStrictHostKeyChecking=no" c hermann@netcup.namibsun.net:/home/hermann

unittest:
  stage: test
  tags:
    - docker
  script:
    - touch a
    - rsync a hermann@netcup.namibsun.net:/home/hermann
#    - python-unittest  # TODO get access to outer files

#deploy_page:
#  stage: deploy
#  only:
#    - master
#    - develop
#  tags:
#    - python3
#    - progstats
#  script:
#    - python3 -m venv virtual && source virtual/bin/activate && pip install ci-scripts
#    - deploy-flask $PROGSTATS_HOME
#
#release_upload:
#  stage: release
#  only:
#    - master
#  tags:
#    - python3
#  script:
#    - python3 -m venv virtual && source virtual/bin/activate && pip install ci-scripts
#    - github-release-upload $(cat version) "$(changelog-reader)"
#    - gitlab-release-upload $(cat version) "$(changelog-reader)"
#
#pypi_upload:
#  stage: release
#  only:
#    - master
#  tags:
#    - python3
#  script:
#    - python3 -m venv virtual && source virtual/bin/activate && pip install ci-scripts
#    - pypi-upload
#
#gitstats:
#  stage: stats
#  tags:
#    - python3
#    - gitstats
#    - progstats
#  script:
#    - python3 -m venv virtual && source virtual/bin/activate && pip install ci-scripts
#    - gitstats-gen
#
#docgen:
#  stage: stats
#  tags:
#    - python3
#    - progstats
#  script:
#    - python3 -m venv virtual && source virtual/bin/activate && pip install ci-scripts
#    - sphinx-docgen
