stages:
  - mirror
  - test
  - deploy
  - release
  - docs

github_mirror:
  stage: mirror
  tags:
    - github_namboy94_push
  script:
    - git checkout master
    - git pull
    - git push git@github.com:namboy94/progstats.git master -f
    - git checkout develop
    - git pull
    - git push git@github.com:namboy94/progstats.git develop -f

stylecheck:
  stage: test
  tags:
    - pycodestyle
  script:
    - pycodestyle .
    
run_unit_tests_with_coverage:
  stage: test
  tags:
    - python3
    - progstats-live
  script:
    - python3 setup.py nosetests -v --with-coverage --cover-package=progstats --cover-branches --cover-erase --cover-html --cover-inclusive
    - rsync -av cover/ /var/www/progstats.namibsun.net/data/coverage/progstats --delete-before

deploy_page:
  stage: deploy
  only:
    - master
    - develop
  tags:
    - progstats-live
    - python3
  script:
    - python3 -m venv virtual
    - source virtual/bin/activate
    - python3 setup.py install
    - deactivate
    - rsync -av virtual /var/www/progstats.namibsun.net/ --delete-after
    - rsync -av progstats.wsgi /var/www/progstats.namibsun.net/

pypi_dist:
  stage: deploy
  only:
    - master
  tags:
    - python3
    - pypi
  script:
    - python3 setup.py register sdist upload
    - python3 setup.py bdist_wheel upload

upload_release_to_github:
  stage: release
  only:
    - master
  tags:
    - python3
  script:
    - mkdir -p artifacts
    - git clone https://gitlab.namibsun.net/namboy94/ci-scripts.git
    - python3 ci-scripts/progstats/changelog-reader/changelog-reader.py -c CHANGELOG -d current_changelog
    - python3 ci-scripts/progstats/github-release-uploader/github-release-uploader.py namboy94 progstats $GITHUB_ACCESS_TOKEN
      $(python3 setup.py -V) current_changelog artifacts -b master

upload_release_to_gitlab:
  stage: release
  only:
    - master
  tags:
    - python3
  script:
    - mkdir -p artifacts
    - git clone https://gitlab.namibsun.net/namboy94/ci-scripts.git
    - python3 ci-scripts/progstats/changelog-reader/changelog-reader.py -c CHANGELOG -d  current_changelog
    - python3 ci-scripts/progstats/gitlab-release-uploader/gitlab-release-uploader.py namboy94 progstats $GITLAB_ACCESS_TOKEN
      $(python3 setup.py -V) current_changelog artifacts -b master -u https://gitlab.namibsun.net

generate_sphinx_documentation:
  stage: docs
  only:
    - master
    - develop
  tags:
    - python3
    - latex
    - progstats-live
  script:
    - python3 -m venv virtual
    - source virtual/bin/activate
    - python3 setup.py install
    - pip install sphinx sphinx_rtd_theme
    - cd doc
    - make buildsource
    - make latexpdf
    - make html
    - rsync -av build/latex/progstats.pdf /var/www/progstats.namibsun.net/data/doc_pdf/progstats.pdf --delete-before
    - rsync -av build/html/ /var/www/progstats.namibsun.net/data/doc_html/progstats --delete-before
    - cd ..
    - deactivate
