stages:
  - test
  - stats
  - deploy
  - release

default:
  image: ubuntu:18.04
  before_script:
    - apt update
    - apt install rsync ssh python3 python3-pip -y
    - pip3 install ci-scripts
    - mkdir -p ~/.ssh
    - echo "$SERVER_ACCESS_KEY" > ~/.ssh/id_rsa
    - chmod 0600 ~/.ssh/id_rsa
    - ssh-keyscan -H $PROGSTATS_DOMAIN > ~/.ssh/known_hosts

stylecheck:
  stage: test
  tags: [docker]
  script: [python-codestyle-check]

unittest:
  stage: test
  tags: [docker]
  script: [python-unittest]

deploy_page:
  stage: deploy
  only: [master, develop]
  tags: [docker]
  script:
    - apt install python3-venv
    - deploy-flask $PROGSTATS_HOME

release_upload:
  stage: release
  only: [master]
  tags: [docker]
  script:
    - github-release-upload $(cat version) "$(changelog-reader)"
    - gitlab-release-upload $(cat version) "$(changelog-reader)"

pypi_upload:
  stage: release
  only: [master]
  tags: [docker]
  script: [pypi-upload]

gitstats:
  stage: stats
  tags: [docker]
  script:
    - apt install gitstats ruby-dev
    - gem install git_stats
    - gitstats-gen

docgen:
  stage: stats
  tags: [docker]
  script: [sphinx-docgen]
