stages:
  - mirror
  - test
  - stats
  - deploy
  - release

default:
  image: namboy94/ci-docker-environment:0.1.0
  before_script:
    - echo "$SERVER_ACCESS_KEY" > ~/.ssh/id_rsa
    - chmod 0600 ~/.ssh/id_rsa

github_mirror:
  stage: mirror
  tags: [docker]
  before_script:
    - echo "$GITHUB_SSH_KEY" > ~/.ssh/id_rsa
    - chmod 0600 ~/.ssh/id_rsa
  script:
    - git-mirror-pusher git@github.com:namboy94/progstats.git master develop

stylecheck:
  stage: test
  tags: [docker]
  script:
    - python-codestyle-check

unittest:
  stage: test
  tags: [docker]
  script:
    - python-unittest

deploy_page:
  stage: deploy
  only: [master, develop]
  tags: [docker]
  script:
    - apt install python3-venv
    - deploy-flask $PROGSTATS_HOME

release_upload:
  stage: release
  only: [master]
  tags: [docker]
  script:
    - github-release-upload $(cat version) "$(changelog-reader)"
    - gitlab-release-upload $(cat version) "$(changelog-reader)"

pypi_upload:
  stage: release
  only: [master]
  tags: [docker]
  script:
    - pypi-upload

gitstats:
  stage: stats
  tags: [docker]
  script:
    - gitstats-gen

docgen:
  stage: stats
  tags: [docker]
  script:
    - sphinx-docgen
