stages:
  - test
  - stats
  - deploy
  - release

default:
  image: python:3.7-buster
  before_script:
    - apt install rsync ssh
    - pip install ci-scripts
    - echo $SERVER_ACCESS_KEY > id_rsa

stylecheck:
  stage: test
  tags: [docker]
  script:
    - python-codestyle-check

unittest:
  stage: test
  tags:
    - docker
  script:
    - touch a
    - rsync -e "ssh -i id_rsa" a hermann@gitlab.namibsun.net:/home/hermann
#    - python-unittest  # TODO get access to outer files

#deploy_page:
#  stage: deploy
#  only:
#    - master
#    - develop
#  tags:
#    - python3
#    - progstats
#  script:
#    - python3 -m venv virtual && source virtual/bin/activate && pip install ci-scripts
#    - deploy-flask $PROGSTATS_HOME
#
#release_upload:
#  stage: release
#  only:
#    - master
#  tags:
#    - python3
#  script:
#    - python3 -m venv virtual && source virtual/bin/activate && pip install ci-scripts
#    - github-release-upload $(cat version) "$(changelog-reader)"
#    - gitlab-release-upload $(cat version) "$(changelog-reader)"
#
#pypi_upload:
#  stage: release
#  only:
#    - master
#  tags:
#    - python3
#  script:
#    - python3 -m venv virtual && source virtual/bin/activate && pip install ci-scripts
#    - pypi-upload
#
#gitstats:
#  stage: stats
#  tags:
#    - python3
#    - gitstats
#    - progstats
#  script:
#    - python3 -m venv virtual && source virtual/bin/activate && pip install ci-scripts
#    - gitstats-gen
#
#docgen:
#  stage: stats
#  tags:
#    - python3
#    - progstats
#  script:
#    - python3 -m venv virtual && source virtual/bin/activate && pip install ci-scripts
#    - sphinx-docgen
