stages:
  - mirror
  - test
  - deploy
  - release

github_mirror:
  stage: mirror
  tags:
    - github_namboy94_push
  script:
    - git checkout master
    - git pull
    - git push git@github.com:namboy94/progstats.git master -f
    - git checkout develop
    - git pull
    - git push git@github.com:namboy94/progstats.git develop -f

stylecheck:
  stage: test
  tags:
    - pycodestyle
  script:
    - pycodestyle .

deploy_page:
  stage: deploy
  only:
    - master
    - develop
  tags:
    - progstats-live
    - python3
  script:
    - echo
    - python3 -m venv virtual
    - source virtual/bin/activate
    - python3 setup.py install
    - deactivate
    - rsync -av virtual /var/www/progstats.namibsun.net/ --delete-after
    - rsync -av progstats.wsgi /var/www/progstats.namibsun.net/

upload_release_to_github:
  stage: release
  only:
    - master
  tags:
    - python
  script:
    - mkdir -p artifacts
    - git clone https://gitlab.namibsun.net/namboy94/ci-scripts.git
    - python ci-scripts/progstats/changelog-reader/changelog-reader.py -c CHANGELOG -d current_changelog
    - python ci-scripts/progstats/github-release-uploader/github-release-uploader.py namboy94 progstats $GITHUB_ACCESS_TOKEN
      $(python3 setup.py -V) current_changelog artifacts -b master

upload_release_to_gitlab:
  stage: release
  only:
    - master
  tags:
    - python
  script:
    - mkdir -p artifacts
    - git clone https://gitlab.namibsun.net/namboy94/ci-scripts.git
    - python ci-scripts/progstats/changelog-reader/changelog-reader.py -c CHANGELOG -d  current_changelog
    - python ci-scripts/progstats/gitlab-release-uploader/gitlab-release-uploader.py namboy94 progstats $GITLAB_ACCESS_TOKEN
      $(python3 setup.py -V) current_changelog artifacts -b master -u https://gitlab.namibsun.net
